//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.02 at 05:29:10 PM CET 
//


package ers.jaxb;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for PartyDetailGrp_Block_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PartyDetailGrp_Block_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{}PartyDetailGrpElements"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}PartyDetailGrpAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartyDetailGrp_Block_t", propOrder = {
    "sub",
    "altPty",
    "reltdPtyDetl"
})
public class PartyDetailGrpBlockT {

    @XmlElement(name = "Sub")
    protected List<PartyDetailSubGrpBlockT> sub;
    @XmlElement(name = "AltPty")
    protected List<PartyDetailAltIDGrpBlockT> altPty;
    @XmlElement(name = "ReltdPtyDetl")
    protected List<RelatedPartyDetailGrpBlockT> reltdPtyDetl;
    @XmlAttribute(name = "ID")
    protected String id;
    @XmlAttribute(name = "Src")
    protected String src;
    @XmlAttribute(name = "R")
    protected BigInteger r;
    @XmlAttribute(name = "Qual")
    protected BigInteger qual;
    @XmlAttribute(name = "Stat")
    protected BigInteger stat;

    /**
     * Gets the value of the sub property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sub property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSub().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyDetailSubGrpBlockT }
     * 
     * 
     */
    public List<PartyDetailSubGrpBlockT> getSub() {
        if (sub == null) {
            sub = new ArrayList<PartyDetailSubGrpBlockT>();
        }
        return this.sub;
    }

    /**
     * Gets the value of the altPty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the altPty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAltPty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyDetailAltIDGrpBlockT }
     * 
     * 
     */
    public List<PartyDetailAltIDGrpBlockT> getAltPty() {
        if (altPty == null) {
            altPty = new ArrayList<PartyDetailAltIDGrpBlockT>();
        }
        return this.altPty;
    }

    /**
     * Gets the value of the reltdPtyDetl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reltdPtyDetl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReltdPtyDetl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelatedPartyDetailGrpBlockT }
     * 
     * 
     */
    public List<RelatedPartyDetailGrpBlockT> getReltdPtyDetl() {
        if (reltdPtyDetl == null) {
            reltdPtyDetl = new ArrayList<RelatedPartyDetailGrpBlockT>();
        }
        return this.reltdPtyDetl;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the src property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrc() {
        return src;
    }

    /**
     * Sets the value of the src property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrc(String value) {
        this.src = value;
    }

    /**
     * Gets the value of the r property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getR() {
        return r;
    }

    /**
     * Sets the value of the r property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setR(BigInteger value) {
        this.r = value;
    }

    /**
     * Gets the value of the qual property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getQual() {
        return qual;
    }

    /**
     * Sets the value of the qual property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setQual(BigInteger value) {
        this.qual = value;
    }

    /**
     * Gets the value of the stat property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getStat() {
        return stat;
    }

    /**
     * Sets the value of the stat property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setStat(BigInteger value) {
        this.stat = value;
    }

}
