//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.02 at 05:29:10 PM CET 
//


package com.opnfi.risk.model.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Batch_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Batch_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{}BatchElements"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}BatchAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Batch_t", propOrder = {
    "hdr",
    "message"
})
public class BatchT {

    @XmlElement(name = "Hdr")
    protected BatchHeaderT hdr;
    @XmlElementRef(name = "Message", type = JAXBElement.class, required = false)
    protected List<JAXBElement<? extends AbstractMessageT>> message;
    @XmlAttribute(name = "ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the hdr property.
     * 
     * @return
     *     possible object is
     *     {@link BatchHeaderT }
     *     
     */
    public BatchHeaderT getHdr() {
        return hdr;
    }

    /**
     * Sets the value of the hdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatchHeaderT }
     *     
     */
    public void setHdr(BatchHeaderT value) {
        this.hdr = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the message property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link MarginRequirementInquiryAckMessageT }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link PartyRiskLimitsRequestMessageT }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link PartyRiskLimitsDefinitionRequestMessageT }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link MarginRequirementInquiryMessageT }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link PartyRiskLimitsDefinitionRequestAckMessageT }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TradingSessionStatusRequestMessageT }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link MarginRequirementReportMessageT }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link PositionReportMessageT }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link PartyRiskLimitsReportMessageT }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link AbstractMessageT }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link BusinessMessageRejectMessageT }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link TradingSessionStatusMessageT }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends AbstractMessageT>> getMessage() {
        if (message == null) {
            message = new ArrayList<JAXBElement<? extends AbstractMessageT>>();
        }
        return this.message;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

}
