//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.02 at 05:29:10 PM CET 
//


package com.opnfi.risk.model.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ComplexEventDates_Block_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexEventDates_Block_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{}ComplexEventDatesElements"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}ComplexEventDatesAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexEventDates_Block_t", propOrder = {
    "evntTms"
})
public class ComplexEventDatesBlockT {

    @XmlElement(name = "EvntTms")
    protected List<ComplexEventTimesBlockT> evntTms;

    /**
     * Gets the value of the evntTms property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the evntTms property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEvntTms().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComplexEventTimesBlockT }
     * 
     * 
     */
    public List<ComplexEventTimesBlockT> getEvntTms() {
        if (evntTms == null) {
            evntTms = new ArrayList<ComplexEventTimesBlockT>();
        }
        return this.evntTms;
    }

}
