# The secrets should be base64 encoded
apiVersion: v1
kind: Secret
metadata:
  name: ui-secret
  namespace: ttsave
  labels:
    app: dave
    layer: frontend
    project: dave
data:
  http.private_key: XXX
  http.public_key: XXX
