//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.02 at 05:29:10 PM CET 
//


package ers.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * BusinessMessageReject can be found in Volume 1 of the
 * 						specification
 * 
 * <p>Java class for BusinessMessageReject_message_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BusinessMessageReject_message_t">
 *   &lt;complexContent>
 *     &lt;extension base="{}Abstract_message_t">
 *       &lt;sequence>
 *         &lt;group ref="{}BusinessMessageRejectElements"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}BusinessMessageRejectAttributes"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusinessMessageReject_message_t")
public class BusinessMessageRejectMessageT
    extends AbstractMessageT
{

    @XmlAttribute(name = "RefMsgTyp", required = true)
    protected String refMsgTyp;
    @XmlAttribute(name = "BizRejRsn", required = true)
    protected BigInteger bizRejRsn;
    @XmlAttribute(name = "Txt")
    protected String txt;

    /**
     * Gets the value of the refMsgTyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefMsgTyp() {
        return refMsgTyp;
    }

    /**
     * Sets the value of the refMsgTyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefMsgTyp(String value) {
        this.refMsgTyp = value;
    }

    /**
     * Gets the value of the bizRejRsn property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getBizRejRsn() {
        return bizRejRsn;
    }

    /**
     * Sets the value of the bizRejRsn property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setBizRejRsn(BigInteger value) {
        this.bizRejRsn = value;
    }

    /**
     * Gets the value of the txt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxt() {
        return txt;
    }

    /**
     * Sets the value of the txt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxt(String value) {
        this.txt = value;
    }

}
