//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.02 at 05:29:10 PM CET 
//


package ers.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}Message"/>
 *         &lt;element name="Batch" type="{}Batch_t" maxOccurs="unbounded"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{}FixmlAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "message",
    "batch"
})
@XmlRootElement(name = "FIXML")
public class FIXML {

    @XmlElementRef(name = "Message", type = JAXBElement.class, required = false)
    protected JAXBElement<? extends AbstractMessageT> message;
    @XmlElement(name = "Batch")
    protected List<BatchT> batch;
    @XmlAttribute(name = "v")
    protected String v;
    @XmlAttribute(name = "s")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar s;

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link MarginRequirementInquiryAckMessageT }{@code >}
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link PartyRiskLimitsRequestMessageT }{@code >}
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link PartyRiskLimitsDefinitionRequestMessageT }{@code >}
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link MarginRequirementInquiryMessageT }{@code >}
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link PartyRiskLimitsDefinitionRequestAckMessageT }{@code >}
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link TradingSessionStatusRequestMessageT }{@code >}
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link MarginRequirementReportMessageT }{@code >}
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link PositionReportMessageT }{@code >}
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link PartyRiskLimitsReportMessageT }{@code >}
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link AbstractMessageT }{@code >}
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link BusinessMessageRejectMessageT }{@code >}
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link TradingSessionStatusMessageT }{@code >}
     *
     */
    public JAXBElement<? extends AbstractMessageT> getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     *
     * @param value
     *     allowed object is
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link MarginRequirementInquiryAckMessageT }{@code >}
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link PartyRiskLimitsRequestMessageT }{@code >}
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link PartyRiskLimitsDefinitionRequestMessageT }{@code >}
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link MarginRequirementInquiryMessageT }{@code >}
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link PartyRiskLimitsDefinitionRequestAckMessageT }{@code >}
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link TradingSessionStatusRequestMessageT }{@code >}
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link MarginRequirementReportMessageT }{@code >}
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link PositionReportMessageT }{@code >}
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link PartyRiskLimitsReportMessageT }{@code >}
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link AbstractMessageT }{@code >}
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link BusinessMessageRejectMessageT }{@code >}
     *     {@link javax.xml.bind.JAXBElement }{@code <}{@link TradingSessionStatusMessageT }{@code >}
     *
     */
    public void setMessage(JAXBElement<? extends AbstractMessageT> value) {
        this.message = value;
    }

    /**
     * Gets the value of the batch property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the batch property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBatch().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BatchT }
     *
     *
     */
    public List<BatchT> getBatch() {
        if (batch == null) {
            batch = new ArrayList<BatchT>();
        }
        return this.batch;
    }

    /**
     * Gets the value of the v property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getV() {
        if (v == null) {
            return "FIX.5.0SP2";
        } else {
            return v;
        }
    }

    /**
     * Sets the value of the v property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setV(String value) {
        this.v = value;
    }

    /**
     * Gets the value of the s property.
     *
     * @return
     *     possible object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getS() {
        return s;
    }

    /**
     * Sets the value of the s property.
     *
     * @param value
     *     allowed object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public void setS(XMLGregorianCalendar value) {
        this.s = value;
    }

}
