//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.02 at 05:29:10 PM CET 
//


package ers.jaxb;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Instrument_Block_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Instrument_Block_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{}InstrumentElements"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}InstrumentAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Instrument_Block_t", propOrder = {
    "aid",
    "secXML",
    "evnt",
    "pty",
    "cmplxEvnt"
})
public class InstrumentBlockT {

    @XmlElement(name = "AID")
    protected List<SecAltIDGrpBlockT> aid;
    @XmlElement(name = "SecXML")
    protected SecurityXMLBlockT secXML;
    @XmlElement(name = "Evnt")
    protected List<EvntGrpBlockT> evnt;
    @XmlElement(name = "Pty")
    protected List<InstrumentPartiesBlockT> pty;
    @XmlElement(name = "CmplxEvnt")
    protected List<ComplexEventsBlockT> cmplxEvnt;
    @XmlAttribute(name = "Sym")
    protected String sym;
    @XmlAttribute(name = "ID")
    protected String id;
    @XmlAttribute(name = "Src")
    protected String src;
    @XmlAttribute(name = "MMY")
    protected String mmy;
    @XmlAttribute(name = "StrkPx")
    protected BigDecimal strkPx;
    @XmlAttribute(name = "OptAt")
    protected String optAt;
    @XmlAttribute(name = "PutCall")
    protected BigInteger putCall;

    /**
     * Gets the value of the aid property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aid property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SecAltIDGrpBlockT }
     * 
     * 
     */
    public List<SecAltIDGrpBlockT> getAID() {
        if (aid == null) {
            aid = new ArrayList<SecAltIDGrpBlockT>();
        }
        return this.aid;
    }

    /**
     * Gets the value of the secXML property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityXMLBlockT }
     *     
     */
    public SecurityXMLBlockT getSecXML() {
        return secXML;
    }

    /**
     * Sets the value of the secXML property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityXMLBlockT }
     *     
     */
    public void setSecXML(SecurityXMLBlockT value) {
        this.secXML = value;
    }

    /**
     * Gets the value of the evnt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the evnt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEvnt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EvntGrpBlockT }
     * 
     * 
     */
    public List<EvntGrpBlockT> getEvnt() {
        if (evnt == null) {
            evnt = new ArrayList<EvntGrpBlockT>();
        }
        return this.evnt;
    }

    /**
     * Gets the value of the pty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InstrumentPartiesBlockT }
     * 
     * 
     */
    public List<InstrumentPartiesBlockT> getPty() {
        if (pty == null) {
            pty = new ArrayList<InstrumentPartiesBlockT>();
        }
        return this.pty;
    }

    /**
     * Gets the value of the cmplxEvnt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cmplxEvnt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCmplxEvnt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComplexEventsBlockT }
     * 
     * 
     */
    public List<ComplexEventsBlockT> getCmplxEvnt() {
        if (cmplxEvnt == null) {
            cmplxEvnt = new ArrayList<ComplexEventsBlockT>();
        }
        return this.cmplxEvnt;
    }

    /**
     * Gets the value of the sym property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSym() {
        return sym;
    }

    /**
     * Sets the value of the sym property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSym(String value) {
        this.sym = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the src property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrc() {
        return src;
    }

    /**
     * Sets the value of the src property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrc(String value) {
        this.src = value;
    }

    /**
     * Gets the value of the mmy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMMY() {
        return mmy;
    }

    /**
     * Sets the value of the mmy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMMY(String value) {
        this.mmy = value;
    }

    /**
     * Gets the value of the strkPx property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigDecimal }
     *
     */
    public BigDecimal getStrkPx() {
        return strkPx;
    }

    /**
     * Sets the value of the strkPx property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigDecimal }
     *
     */
    public void setStrkPx(BigDecimal value) {
        this.strkPx = value;
    }

    /**
     * Gets the value of the optAt property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOptAt() {
        return optAt;
    }

    /**
     * Sets the value of the optAt property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOptAt(String value) {
        this.optAt = value;
    }

    /**
     * Gets the value of the putCall property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getPutCall() {
        return putCall;
    }

    /**
     * Sets the value of the putCall property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setPutCall(BigInteger value) {
        this.putCall = value;
    }

}
