//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.02 at 05:29:10 PM CET 
//


package com.deutscheboerse.risk.dave.model.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cz.scholz.ers package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MgnReqmtInqAck_QNAME = new QName("", "MgnReqmtInqAck");
    private final static QName _PtyRiskLmtDefReqAck_QNAME = new QName("", "PtyRiskLmtDefReqAck");
    private final static QName _PtyRiskLmtDefReq_QNAME = new QName("", "PtyRiskLmtDefReq");
    private final static QName _Message_QNAME = new QName("", "Message");
    private final static QName _PtyRiskLmtRpt_QNAME = new QName("", "PtyRiskLmtRpt");
    private final static QName _BizMsgRej_QNAME = new QName("", "BizMsgRej");
    private final static QName _MgnReqmtRpt_QNAME = new QName("", "MgnReqmtRpt");
    private final static QName _MgnReqmtInq_QNAME = new QName("", "MgnReqmtInq");
    private final static QName _TrdgSesStatReq_QNAME = new QName("", "TrdgSesStatReq");
    private final static QName _TrdgSesStat_QNAME = new QName("", "TrdgSesStat");
    private final static QName _PosRpt_QNAME = new QName("", "PosRpt");
    private final static QName _PtyRiskLmtReq_QNAME = new QName("", "PtyRiskLmtReq");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.scholz.ers
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FIXML }
     * 
     */
    public FIXML createFIXML() {
        return new FIXML();
    }

    /**
     * Create an instance of {@link AbstractMessageT }
     * 
     */
    public AbstractMessageT createAbstractMessageT() {
        return new AbstractMessageT();
    }

    /**
     * Create an instance of {@link BatchT }
     * 
     */
    public BatchT createBatchT() {
        return new BatchT();
    }

    /**
     * Create an instance of {@link MarginRequirementInquiryAckMessageT }
     * 
     */
    public MarginRequirementInquiryAckMessageT createMarginRequirementInquiryAckMessageT() {
        return new MarginRequirementInquiryAckMessageT();
    }

    /**
     * Create an instance of {@link PartyRiskLimitsDefinitionRequestMessageT }
     * 
     */
    public PartyRiskLimitsDefinitionRequestMessageT createPartyRiskLimitsDefinitionRequestMessageT() {
        return new PartyRiskLimitsDefinitionRequestMessageT();
    }

    /**
     * Create an instance of {@link BusinessMessageRejectMessageT }
     * 
     */
    public BusinessMessageRejectMessageT createBusinessMessageRejectMessageT() {
        return new BusinessMessageRejectMessageT();
    }

    /**
     * Create an instance of {@link PositionReportMessageT }
     * 
     */
    public PositionReportMessageT createPositionReportMessageT() {
        return new PositionReportMessageT();
    }

    /**
     * Create an instance of {@link PartyRiskLimitsDefinitionRequestAckMessageT }
     * 
     */
    public PartyRiskLimitsDefinitionRequestAckMessageT createPartyRiskLimitsDefinitionRequestAckMessageT() {
        return new PartyRiskLimitsDefinitionRequestAckMessageT();
    }

    /**
     * Create an instance of {@link PartyRiskLimitsReportMessageT }
     * 
     */
    public PartyRiskLimitsReportMessageT createPartyRiskLimitsReportMessageT() {
        return new PartyRiskLimitsReportMessageT();
    }

    /**
     * Create an instance of {@link TradingSessionStatusRequestMessageT }
     * 
     */
    public TradingSessionStatusRequestMessageT createTradingSessionStatusRequestMessageT() {
        return new TradingSessionStatusRequestMessageT();
    }

    /**
     * Create an instance of {@link MarginRequirementInquiryMessageT }
     * 
     */
    public MarginRequirementInquiryMessageT createMarginRequirementInquiryMessageT() {
        return new MarginRequirementInquiryMessageT();
    }

    /**
     * Create an instance of {@link MarginRequirementReportMessageT }
     * 
     */
    public MarginRequirementReportMessageT createMarginRequirementReportMessageT() {
        return new MarginRequirementReportMessageT();
    }

    /**
     * Create an instance of {@link TradingSessionStatusMessageT }
     * 
     */
    public TradingSessionStatusMessageT createTradingSessionStatusMessageT() {
        return new TradingSessionStatusMessageT();
    }

    /**
     * Create an instance of {@link PartyRiskLimitsRequestMessageT }
     * 
     */
    public PartyRiskLimitsRequestMessageT createPartyRiskLimitsRequestMessageT() {
        return new PartyRiskLimitsRequestMessageT();
    }

    /**
     * Create an instance of {@link LegSecAltIDGrpBlockT }
     * 
     */
    public LegSecAltIDGrpBlockT createLegSecAltIDGrpBlockT() {
        return new LegSecAltIDGrpBlockT();
    }

    /**
     * Create an instance of {@link RequestedPartyRoleGrpBlockT }
     * 
     */
    public RequestedPartyRoleGrpBlockT createRequestedPartyRoleGrpBlockT() {
        return new RequestedPartyRoleGrpBlockT();
    }

    /**
     * Create an instance of {@link PositionAmountDataBlockT }
     * 
     */
    public PositionAmountDataBlockT createPositionAmountDataBlockT() {
        return new PositionAmountDataBlockT();
    }

    /**
     * Create an instance of {@link ComplexEventDatesBlockT }
     * 
     */
    public ComplexEventDatesBlockT createComplexEventDatesBlockT() {
        return new ComplexEventDatesBlockT();
    }

    /**
     * Create an instance of {@link RelatedPartyDetailAltIDGrpBlockT }
     * 
     */
    public RelatedPartyDetailAltIDGrpBlockT createRelatedPartyDetailAltIDGrpBlockT() {
        return new RelatedPartyDetailAltIDGrpBlockT();
    }

    /**
     * Create an instance of {@link InstrmtLegGrpBlockT }
     * 
     */
    public InstrmtLegGrpBlockT createInstrmtLegGrpBlockT() {
        return new InstrmtLegGrpBlockT();
    }

    /**
     * Create an instance of {@link SecurityXMLBlockT }
     * 
     */
    public SecurityXMLBlockT createSecurityXMLBlockT() {
        return new SecurityXMLBlockT();
    }

    /**
     * Create an instance of {@link UnderlyingStipulationsBlockT }
     * 
     */
    public UnderlyingStipulationsBlockT createUnderlyingStipulationsBlockT() {
        return new UnderlyingStipulationsBlockT();
    }

    /**
     * Create an instance of {@link PosUndInstrmtGrpBlockT }
     * 
     */
    public PosUndInstrmtGrpBlockT createPosUndInstrmtGrpBlockT() {
        return new PosUndInstrmtGrpBlockT();
    }

    /**
     * Create an instance of {@link RiskLimitTypesGrpBlockT }
     * 
     */
    public RiskLimitTypesGrpBlockT createRiskLimitTypesGrpBlockT() {
        return new RiskLimitTypesGrpBlockT();
    }

    /**
     * Create an instance of {@link InstrumentScopeSecurityAltIDGrpBlockT }
     * 
     */
    public InstrumentScopeSecurityAltIDGrpBlockT createInstrumentScopeSecurityAltIDGrpBlockT() {
        return new InstrumentScopeSecurityAltIDGrpBlockT();
    }

    /**
     * Create an instance of {@link PartyRelationshipGrpBlockT }
     * 
     */
    public PartyRelationshipGrpBlockT createPartyRelationshipGrpBlockT() {
        return new PartyRelationshipGrpBlockT();
    }

    /**
     * Create an instance of {@link MessageHeaderT }
     * 
     */
    public MessageHeaderT createMessageHeaderT() {
        return new MessageHeaderT();
    }

    /**
     * Create an instance of {@link RiskLimitsGrpBlockT }
     * 
     */
    public RiskLimitsGrpBlockT createRiskLimitsGrpBlockT() {
        return new RiskLimitsGrpBlockT();
    }

    /**
     * Create an instance of {@link ComplexEventTimesBlockT }
     * 
     */
    public ComplexEventTimesBlockT createComplexEventTimesBlockT() {
        return new ComplexEventTimesBlockT();
    }

    /**
     * Create an instance of {@link SecAltIDGrpBlockT }
     * 
     */
    public SecAltIDGrpBlockT createSecAltIDGrpBlockT() {
        return new SecAltIDGrpBlockT();
    }

    /**
     * Create an instance of {@link RiskInstrumentScopeGrpBlockT }
     * 
     */
    public RiskInstrumentScopeGrpBlockT createRiskInstrumentScopeGrpBlockT() {
        return new RiskInstrumentScopeGrpBlockT();
    }

    /**
     * Create an instance of {@link PartyRiskLimitsGrpBlockT }
     * 
     */
    public PartyRiskLimitsGrpBlockT createPartyRiskLimitsGrpBlockT() {
        return new PartyRiskLimitsGrpBlockT();
    }

    /**
     * Create an instance of {@link RelatedPartyDetailSubGrpBlockT }
     * 
     */
    public RelatedPartyDetailSubGrpBlockT createRelatedPartyDetailSubGrpBlockT() {
        return new RelatedPartyDetailSubGrpBlockT();
    }

    /**
     * Create an instance of {@link RiskWarningLevelGrpBlockT }
     * 
     */
    public RiskWarningLevelGrpBlockT createRiskWarningLevelGrpBlockT() {
        return new RiskWarningLevelGrpBlockT();
    }

    /**
     * Create an instance of {@link PositionQtyBlockT }
     * 
     */
    public PositionQtyBlockT createPositionQtyBlockT() {
        return new PositionQtyBlockT();
    }

    /**
     * Create an instance of {@link NstdPtysSubGrpBlockT }
     * 
     */
    public NstdPtysSubGrpBlockT createNstdPtysSubGrpBlockT() {
        return new NstdPtysSubGrpBlockT();
    }

    /**
     * Create an instance of {@link InstrumentPartiesBlockT }
     * 
     */
    public InstrumentPartiesBlockT createInstrumentPartiesBlockT() {
        return new InstrumentPartiesBlockT();
    }

    /**
     * Create an instance of {@link UndSecAltIDGrpBlockT }
     * 
     */
    public UndSecAltIDGrpBlockT createUndSecAltIDGrpBlockT() {
        return new UndSecAltIDGrpBlockT();
    }

    /**
     * Create an instance of {@link RelatedInstrumentGrpBlockT }
     * 
     */
    public RelatedInstrumentGrpBlockT createRelatedInstrumentGrpBlockT() {
        return new RelatedInstrumentGrpBlockT();
    }

    /**
     * Create an instance of {@link ComplexEventsBlockT }
     * 
     */
    public ComplexEventsBlockT createComplexEventsBlockT() {
        return new ComplexEventsBlockT();
    }

    /**
     * Create an instance of {@link InstrumentPtysSubGrpBlockT }
     * 
     */
    public InstrumentPtysSubGrpBlockT createInstrumentPtysSubGrpBlockT() {
        return new InstrumentPtysSubGrpBlockT();
    }

    /**
     * Create an instance of {@link EvntGrpBlockT }
     * 
     */
    public EvntGrpBlockT createEvntGrpBlockT() {
        return new EvntGrpBlockT();
    }

    /**
     * Create an instance of {@link RequestingPartySubGrpBlockT }
     * 
     */
    public RequestingPartySubGrpBlockT createRequestingPartySubGrpBlockT() {
        return new RequestingPartySubGrpBlockT();
    }

    /**
     * Create an instance of {@link UndlyInstrumentPtysSubGrpBlockT }
     * 
     */
    public UndlyInstrumentPtysSubGrpBlockT createUndlyInstrumentPtysSubGrpBlockT() {
        return new UndlyInstrumentPtysSubGrpBlockT();
    }

    /**
     * Create an instance of {@link PartyDetailAltSubGrpBlockT }
     * 
     */
    public PartyDetailAltSubGrpBlockT createPartyDetailAltSubGrpBlockT() {
        return new PartyDetailAltSubGrpBlockT();
    }

    /**
     * Create an instance of {@link UnderlyingInstrumentBlockT }
     * 
     */
    public UnderlyingInstrumentBlockT createUnderlyingInstrumentBlockT() {
        return new UnderlyingInstrumentBlockT();
    }

    /**
     * Create an instance of {@link HopGrpBlockT }
     * 
     */
    public HopGrpBlockT createHopGrpBlockT() {
        return new HopGrpBlockT();
    }

    /**
     * Create an instance of {@link BatchHeaderT }
     * 
     */
    public BatchHeaderT createBatchHeaderT() {
        return new BatchHeaderT();
    }

    /**
     * Create an instance of {@link NestedPartiesBlockT }
     * 
     */
    public NestedPartiesBlockT createNestedPartiesBlockT() {
        return new NestedPartiesBlockT();
    }

    /**
     * Create an instance of {@link InstrumentLegBlockT }
     * 
     */
    public InstrumentLegBlockT createInstrumentLegBlockT() {
        return new InstrumentLegBlockT();
    }

    /**
     * Create an instance of {@link InstrumentBlockT }
     * 
     */
    public InstrumentBlockT createInstrumentBlockT() {
        return new InstrumentBlockT();
    }

    /**
     * Create an instance of {@link RelatedPartyDetailAltSubGrpBlockT }
     * 
     */
    public RelatedPartyDetailAltSubGrpBlockT createRelatedPartyDetailAltSubGrpBlockT() {
        return new RelatedPartyDetailAltSubGrpBlockT();
    }

    /**
     * Create an instance of {@link PartyRiskLimitsAckGrpBlockT }
     * 
     */
    public PartyRiskLimitsAckGrpBlockT createPartyRiskLimitsAckGrpBlockT() {
        return new PartyRiskLimitsAckGrpBlockT();
    }

    /**
     * Create an instance of {@link PartiesBlockT }
     * 
     */
    public PartiesBlockT createPartiesBlockT() {
        return new PartiesBlockT();
    }

    /**
     * Create an instance of {@link RelatedPartyDetailGrpBlockT }
     * 
     */
    public RelatedPartyDetailGrpBlockT createRelatedPartyDetailGrpBlockT() {
        return new RelatedPartyDetailGrpBlockT();
    }

    /**
     * Create an instance of {@link UndlyInstrumentPartiesBlockT }
     * 
     */
    public UndlyInstrumentPartiesBlockT createUndlyInstrumentPartiesBlockT() {
        return new UndlyInstrumentPartiesBlockT();
    }

    /**
     * Create an instance of {@link RequestedRiskLimitTypesGrpBlockT }
     * 
     */
    public RequestedRiskLimitTypesGrpBlockT createRequestedRiskLimitTypesGrpBlockT() {
        return new RequestedRiskLimitTypesGrpBlockT();
    }

    /**
     * Create an instance of {@link MarginAmountBlockT }
     * 
     */
    public MarginAmountBlockT createMarginAmountBlockT() {
        return new MarginAmountBlockT();
    }

    /**
     * Create an instance of {@link PtysSubGrpBlockT }
     * 
     */
    public PtysSubGrpBlockT createPtysSubGrpBlockT() {
        return new PtysSubGrpBlockT();
    }

    /**
     * Create an instance of {@link ApplicationSequenceControlBlockT }
     * 
     */
    public ApplicationSequenceControlBlockT createApplicationSequenceControlBlockT() {
        return new ApplicationSequenceControlBlockT();
    }

    /**
     * Create an instance of {@link PartyRiskLimitsUpdateGrpBlockT }
     * 
     */
    public PartyRiskLimitsUpdateGrpBlockT createPartyRiskLimitsUpdateGrpBlockT() {
        return new PartyRiskLimitsUpdateGrpBlockT();
    }

    /**
     * Create an instance of {@link PartyDetailGrpBlockT }
     * 
     */
    public PartyDetailGrpBlockT createPartyDetailGrpBlockT() {
        return new PartyDetailGrpBlockT();
    }

    /**
     * Create an instance of {@link MarginReqmtInqQualGrpBlockT }
     * 
     */
    public MarginReqmtInqQualGrpBlockT createMarginReqmtInqQualGrpBlockT() {
        return new MarginReqmtInqQualGrpBlockT();
    }

    /**
     * Create an instance of {@link UnderlyingAmountBlockT }
     * 
     */
    public UnderlyingAmountBlockT createUnderlyingAmountBlockT() {
        return new UnderlyingAmountBlockT();
    }

    /**
     * Create an instance of {@link BaseHeaderT }
     * 
     */
    public BaseHeaderT createBaseHeaderT() {
        return new BaseHeaderT();
    }

    /**
     * Create an instance of {@link RequestingPartyGrpBlockT }
     * 
     */
    public RequestingPartyGrpBlockT createRequestingPartyGrpBlockT() {
        return new RequestingPartyGrpBlockT();
    }

    /**
     * Create an instance of {@link PartyDetailSubGrpBlockT }
     * 
     */
    public PartyDetailSubGrpBlockT createPartyDetailSubGrpBlockT() {
        return new PartyDetailSubGrpBlockT();
    }

    /**
     * Create an instance of {@link PartyDetailAltIDGrpBlockT }
     * 
     */
    public PartyDetailAltIDGrpBlockT createPartyDetailAltIDGrpBlockT() {
        return new PartyDetailAltIDGrpBlockT();
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link MarginRequirementInquiryAckMessageT }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "MgnReqmtInqAck", substitutionHeadNamespace = "", substitutionHeadName = "Message")
    public JAXBElement<MarginRequirementInquiryAckMessageT> createMgnReqmtInqAck(MarginRequirementInquiryAckMessageT value) {
        return new JAXBElement<MarginRequirementInquiryAckMessageT>(_MgnReqmtInqAck_QNAME, MarginRequirementInquiryAckMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link PartyRiskLimitsDefinitionRequestAckMessageT }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "PtyRiskLmtDefReqAck", substitutionHeadNamespace = "", substitutionHeadName = "Message")
    public JAXBElement<PartyRiskLimitsDefinitionRequestAckMessageT> createPtyRiskLmtDefReqAck(PartyRiskLimitsDefinitionRequestAckMessageT value) {
        return new JAXBElement<PartyRiskLimitsDefinitionRequestAckMessageT>(_PtyRiskLmtDefReqAck_QNAME, PartyRiskLimitsDefinitionRequestAckMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link PartyRiskLimitsDefinitionRequestMessageT }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "PtyRiskLmtDefReq", substitutionHeadNamespace = "", substitutionHeadName = "Message")
    public JAXBElement<PartyRiskLimitsDefinitionRequestMessageT> createPtyRiskLmtDefReq(PartyRiskLimitsDefinitionRequestMessageT value) {
        return new JAXBElement<PartyRiskLimitsDefinitionRequestMessageT>(_PtyRiskLmtDefReq_QNAME, PartyRiskLimitsDefinitionRequestMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link AbstractMessageT }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "Message")
    public JAXBElement<AbstractMessageT> createMessage(AbstractMessageT value) {
        return new JAXBElement<AbstractMessageT>(_Message_QNAME, AbstractMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link PartyRiskLimitsReportMessageT }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "PtyRiskLmtRpt", substitutionHeadNamespace = "", substitutionHeadName = "Message")
    public JAXBElement<PartyRiskLimitsReportMessageT> createPtyRiskLmtRpt(PartyRiskLimitsReportMessageT value) {
        return new JAXBElement<PartyRiskLimitsReportMessageT>(_PtyRiskLmtRpt_QNAME, PartyRiskLimitsReportMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link BusinessMessageRejectMessageT }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "BizMsgRej", substitutionHeadNamespace = "", substitutionHeadName = "Message")
    public JAXBElement<BusinessMessageRejectMessageT> createBizMsgRej(BusinessMessageRejectMessageT value) {
        return new JAXBElement<BusinessMessageRejectMessageT>(_BizMsgRej_QNAME, BusinessMessageRejectMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link MarginRequirementReportMessageT }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "MgnReqmtRpt", substitutionHeadNamespace = "", substitutionHeadName = "Message")
    public JAXBElement<MarginRequirementReportMessageT> createMgnReqmtRpt(MarginRequirementReportMessageT value) {
        return new JAXBElement<MarginRequirementReportMessageT>(_MgnReqmtRpt_QNAME, MarginRequirementReportMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link MarginRequirementInquiryMessageT }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "MgnReqmtInq", substitutionHeadNamespace = "", substitutionHeadName = "Message")
    public JAXBElement<MarginRequirementInquiryMessageT> createMgnReqmtInq(MarginRequirementInquiryMessageT value) {
        return new JAXBElement<MarginRequirementInquiryMessageT>(_MgnReqmtInq_QNAME, MarginRequirementInquiryMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link TradingSessionStatusRequestMessageT }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "TrdgSesStatReq", substitutionHeadNamespace = "", substitutionHeadName = "Message")
    public JAXBElement<TradingSessionStatusRequestMessageT> createTrdgSesStatReq(TradingSessionStatusRequestMessageT value) {
        return new JAXBElement<TradingSessionStatusRequestMessageT>(_TrdgSesStatReq_QNAME, TradingSessionStatusRequestMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link TradingSessionStatusMessageT }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "TrdgSesStat", substitutionHeadNamespace = "", substitutionHeadName = "Message")
    public JAXBElement<TradingSessionStatusMessageT> createTrdgSesStat(TradingSessionStatusMessageT value) {
        return new JAXBElement<TradingSessionStatusMessageT>(_TrdgSesStat_QNAME, TradingSessionStatusMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link PositionReportMessageT }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "PosRpt", substitutionHeadNamespace = "", substitutionHeadName = "Message")
    public JAXBElement<PositionReportMessageT> createPosRpt(PositionReportMessageT value) {
        return new JAXBElement<PositionReportMessageT>(_PosRpt_QNAME, PositionReportMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link PartyRiskLimitsRequestMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PtyRiskLmtReq", substitutionHeadNamespace = "", substitutionHeadName = "Message")
    public JAXBElement<PartyRiskLimitsRequestMessageT> createPtyRiskLmtReq(PartyRiskLimitsRequestMessageT value) {
        return new JAXBElement<PartyRiskLimitsRequestMessageT>(_PtyRiskLmtReq_QNAME, PartyRiskLimitsRequestMessageT.class, null, value);
    }

}
