//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.02 at 05:29:10 PM CET 
//


package com.deutscheboerse.risk.dave.model.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SettlSessID_enum_t.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SettlSessID_enum_t">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ITD"/>
 *     &lt;enumeration value="RTH"/>
 *     &lt;enumeration value="ETH"/>
 *     &lt;enumeration value="EOD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SettlSessID_enum_t")
@XmlEnum
public enum SettlSessIDEnumT {

    ITD,
    RTH,
    ETH,
    EOD;

    public String value() {
        return name();
    }

    public static SettlSessIDEnumT fromValue(String v) {
        return valueOf(v);
    }

}
